version: '2'
services:
    app1:
        networks:
            test:
        build:
            context: .
            dockerfile: Dockerfile.java
        expose:
        - "8080"
        depends_on:
        - mysql
    app2:
        networks:
            test:
        build:
            context: .
            dockerfile: Dockerfile.java
        expose:
        - "8080"
        depends_on:
        - mysql
    proxy:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        networks:
            test:
        ports:
            - '8080:80'
        depends_on:
             - app1
             - app2

    mysql:
        networks:
             test:
        image: mysql:5.7.8
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=petclinic
            - MYSQL_DATABASE=petclinic
        volumes:
            - "./conf.d:/etc/mysql/conf.d:ro"
            - ./src/main/resources/db/mysql:/docker-entrypoint-initdb.d
networks:
  test:
    driver: bridge
