version: '2'
services:
    app1:
        networks:
            test:
        image: ormaman/alibaba-nodejs4:20
        expose:
        - "8080"
    app2:
        networks:
            test:
        image: ormaman/alibaba-nodejs4:20
        expose:
        - "8080" 

    proxy:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        networks:
            test:
        ports:
            - '8080:80'
    
    mysql:
        networks:
             test:
        image: mysql:5.7.8
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
        depends_on:
        - app1
        volumes:
            - "./conf.d:/etc/mysql/conf.d:ro"
            - ./src/main/resources/db/mysql:/docker-entrypoint-initdb.d
networks:
  test:
    driver: bridge
